//AUTH TYPES
export const LOGIN_USER = "LOGIN_USER";

//CART TYPES
export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const SUBTRACT_QUANTITY_ITEM = "SUBTRACT_QUANTITY_ITEM";
export const ADD_QUANTITY_ITEM = "ADD_QUANTITY_ITEM";
