//AUTH TYPES
export const LOGIN_USER = "LOGIN_USER";

//CART TYPES
export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const SUBTRACT_QUANTITY_ITEM = "SUBTRACT_QUANTITY_ITEM";
export const ADD_QUANTITY_ITEM = "ADD_QUANTITY_ITEM";

//SHOP TYPES
export const FETCH_COLLECTIONS_START = "FETCH_COLLECTIONS_START";
export const FETCH_COLLECTIONS_SUCCESS = "FETCH_COLLECTIONS_SUCCESS";
export const FETCH_COLLECTIONS_FAILURE = "FETCH_COLLECTIONS_FAILURE";
export const FETCH_COLLECTIONS_CATEGORY = "FETCH_COLLECTIONS_CATEGORY";
